apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  selector:
    matchLabels:
      app: order-service-app
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
        - name: "order-service"
          image: "szalaigeri/order-service:1.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: WAREHOUSE_URL
              value: {{ .Values.warehouse.url }}