apiVersion: v1
kind: Service
metadata:
  name: order-service-internal
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: order-service
    targetPort: 8080
    protocol: TCP
  selector:
    app: order-service-app