apiVersion: v1
kind: Service
metadata:
  name: warehouse-service-internal
spec:
  type: ClusterIP
  ports:
    - port: 8081
      name: warehouse
      targetPort: 8081
      protocol: TCP
  selector:
    app: warehouse-app